# This file defines the ArgoCD Application resource for managing the ArgoCD Monitor CronJob.
# It ensures the CronJob is synchronized and managed by ArgoCD.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-monitor
  namespace: argocd
spec:
  project: kubeops  # Asegúrate de que este proyecto permita el namespace poc y los recursos necesarios
  source:
    repoURL: https://github.com/JaimeHenaoChallange/opcion2.git
    targetRevision: HEAD
    path: scripts/cronjob  # Asegúrate de que esta ruta no incluya duplicados
  destination:
    server: https://kubernetes.default.svc
    namespace: poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
