# This file defines the CronJob resource for the ArgoCD Monitor.
# The CronJob periodically monitors ArgoCD applications and sends notifications.

apiVersion: batch/v1
kind: CronJob
metadata:
  name: argocd-monitor
  namespace: poc
  labels:
    app.kubernetes.io/name: argocd-monitor
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app.kubernetes.io/name: argocd-monitor
        spec:
          priorityClassName: high-priority
          serviceAccountName: default
          containers:
          - name: argocd-monitor
            image: jaimehenao8126/script_local-argocd-monitor:latest
            imagePullPolicy: Always
            env:
            - name: ARGOCD_API
              value: "https://argocd-server.argocd.svc.cluster.local:443" # DNS interno
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-token-secret
                  key: token
            - name: SLACK_WEBHOOK_URL
              value: "https://hooks.slack.com/services/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"
            resources:
              requests:
                memory: "64Mi"
                cpu: "100m"
              limits:
                memory: "128Mi"
                cpu: "200m"
          restartPolicy: OnFailure
