# This file defines the Role resource for the ArgoCD Monitor.
# It grants permissions to access Kubernetes resources required by the monitor.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-monitor-role
  namespace: poc
rules:
- apiGroups: [""]  # Recursos del API core
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["argoproj.io"]  # Recursos de ArgoCD
  resources: ["applications"]
  verbs: ["get", "list", "watch"]
