version: "3.8"
services:
  argocd-monitor:
    build: .
    container_name: argocd-monitor
    network_mode: host
    environment:
      - ARGOCD_API=https://localhost:8080/api/v1
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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
    restart: always
