apiVersion: batch/v1
kind: CronJob
metadata:
  name: argocd-monitor
  namespace: poc  # Cambiado a poc
  labels:
    app.kubernetes.io/name: argocd-monitor
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1  # Mantén solo 1 job exitoso para depuración
  failedJobsHistoryLimit: 1      # Mantén solo 1 job fallido para depuración
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: argocd-monitor
        spec:
          serviceAccountName: default
          containers:
          - name: argocd-monitor
            image: jaimehenao8126/script_local-argocd-monitor:latest
            imagePullPolicy: Always
            env:
            - name: ARGOCD_API
              value: "https://localhost:8080/api/v1"
            - name: SLACK_WEBHOOK_URL
              value: "https://hooks.slack.com/services/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"
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-token-secret
                  key: token  # Usa un secreto para mayor seguridad
            resources:
              requests:
                memory: "128Mi"
                cpu: "250m"
              limits:
                memory: "256Mi"
                cpu: "500m"
          restartPolicy: OnFailure
