apiVersion: v1
kind: Secret
metadata:
  name: argocd-token-secret
  namespace: poc
type: Opaque
data:
  token: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKaGNtZHZZMlFpTENKemRXSWlPaUpoWkcxcGJqcGhjR2xMWlhraUxDSnVZbVlpT2pFM05ETTNNVGN3TWpVc0ltbGhkQ0k2TVRjME16Y3hOekF5TlN3aWFuUnBJam9pTURCalpqVmhZemt0WW1Sak15MDBaVEU1TFdFNE56RXRNV05pT1RVd09EUmlNRFV3SW4wLlpnWklzZC1rdHExVUotOUl1bXFMTmdYZV9KRkRLYWd5RUN5VTkxSkdCZDQ=
