apiVersion: batch/v1
kind: CronJob
metadata:
  name: argocd-monitor
  namespace: poc
  labels:
    app.kubernetes.io/name: argocd-monitor
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1  # Mantén solo 1 job exitoso
  failedJobsHistoryLimit: 1      # Mantén solo 1 job fallido
  concurrencyPolicy: Forbid       # Evita que se ejecuten múltiples jobs en paralelo
  startingDeadlineSeconds: 60     # Tiempo máximo para iniciar un job antes de descartarlo
  jobTemplate:
    spec:
      backoffLimit: 2             # Reintenta un máximo de 2 veces antes de fallar
      template:
        metadata:
          labels:
            app.kubernetes.io/name: argocd-monitor
        spec:
          priorityClassName: high-priority
          serviceAccountName: default
          containers:
          - name: argocd-monitor
            image: jaimehenao8126/script_local-argocd-monitor:latest
            imagePullPolicy: Always
            env:
            - name: ARGOCD_API
              value: "https://localhost:8080/api/v1"
            - name: SLACK_WEBHOOK_URL
              value: "https://hooks.slack.com/services/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"
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-token-secret
                  key: token
            resources:
              requests:
                memory: "64Mi"
                cpu: "100m"
              limits:
                memory: "128Mi"
                cpu: "200m"
          restartPolicy: OnFailure
