apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-monitor-rolebinding
  namespace: poc
subjects:
- kind: ServiceAccount
  name: default
  namespace: poc
roleRef:
  kind: Role
  name: argocd-monitor-role
  apiGroup: rbac.authorization.k8s.io
