apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-monitor-clusterrole
rules:
- apiGroups: [""]  # Recursos del API core
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["argoproj.io"]  # Recursos de ArgoCD
  resources: ["applications"]
  verbs: ["get", "list", "watch"]
