# This file defines the RoleBinding resource for the ArgoCD Monitor.
# It binds the Role to the default ServiceAccount in the namespace `poc`.

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-monitor-rolebinding
  namespace: poc
subjects:
- kind: ServiceAccount
  name: default
  namespace: poc
roleRef:
  kind: Role  # Asegúrate de que coincida con el recurso Role
  name: argocd-monitor-role
  apiGroup: rbac.authorization.k8s.io
