apiVersion: rbac.authorization.k8s.io/v1
kind: Role  # Cambiado de ClusterRole a Role
metadata:
  name: argocd-monitor-role
  namespace: poc  # Limitado al namespace poc
rules:
- apiGroups: [""]  # Recursos del API core
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["argoproj.io"]  # Recursos de ArgoCD
  resources: ["applications"]
  verbs: ["get", "list", "watch"]
